name: API Testing on Chrome - Cypress Tests - Cypress API Plugin

on: 
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    name: Cypress API Testing
    steps:
      - uses: actions/checkout@v4

      - name: Cypress E2E Testing
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: npm install
          runTests: true
          
      - name: Relatorio dos Testes - Evidencias - Screenshots - Failed
        uses: actions/upload-artifact@v4 
        if: failure()
        with:
          name: Relatorio dos Testes - Evidencias - Screenshots - Failed
          path: cypress/screenshots

      - name: Relatorio dos Testes - Evidencias - Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Relatorio dos Testes - Videos
          path: cypress/videos

      - name: Relatorio dos Testes - HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Relatorio dos Testes - HTML 
          path: cypress/reports/html/
          if-no-files-found: error

      - name: Implantar Resultados no Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "**/reports/html/"                                
